[programs.devnet]
blog = "9ZXF31HfNPdhenwQ8kMZQrEdzrEcSKiLg4qFKFgbpV8z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/annasudol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
